Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,6 +28,10 @@ jobs:
       - name: Install dependencies
         run: pip install jinja2
 
+      - name: Ensure script downloaded
+        run: |
+          test -f generate_readme.py || (echo "Script not found!" && exit 1)
+
       - name: Generate README
         env:
           REPO_NAME: ${{ github.event.repository.name }}
@@ -35,7 +39,6 @@ jobs:
           REPO_OWNER: ${{ github.event.repository.owner.login }}
           REPO_CREATED_AT: ${{ github.event.repository.created_at }}
         run: |
-          python AutoReadme/generate_readme.py
           python generate_readme.py
 
       - name: Commit and push README.md
